openapi: 3.0.0
info:
  title: Payments
  version: '1.0'
  description: The Lianlian Global Payments API is designed for Marketplaces to link their accounts with Lianlian merchant accounts and send them cross currency payments.
  contact:
    name: David Dawson
    email: david.dawson@lianlian.com
paths:
  /merchants:
    post:
      summary: Start New Merchant Registration
      operationId: post-merchants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchant'
              examples:
                Example 1:
                  value:
                    shop_url: 'https://www.wish.com/merchant/wish001'
                    note: rft
                    registration_complete: true
                    status: success
                    id: '8866003800000564'
                    merchant_client_id: wish001
                Example 2:
                  value:
                    registration_url: 'https://gtest.lianlianpay-inc.com/auth/platform?platformName=WISH&handleCode=e458644e-f0bb-4536-a42a-d02c7020946d'
                    shop_url: 'https://www.wish.com/merchant/wish002'
                    note: rft
                    registration_complete: false
                    merchant_client_id: wish002
        '400':
          description: |
            Codes:

            | Code | Description |Client Action | LianLian Action |
            |------|------------|---------|---------|
            |999995 | Invalid Parameter |Client updates request body values according to error code returned by Lianlian.|Waits for a new request|
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                '999995':
                  value:
                    code: '999995'
                    message: "[merchant_client_id] can't be empty."
      description: "Starts asynchronous process of registering a new merchant with LianLian.  \n\nOn successful return, if `registration_complete` is `false`, platform shall use `registration_url` to redirect the merchant to in order to begin the LianLian Registration Experience.  \n\nWhen registration is successfully completed the user will be redirected to the passed in `redirect_url`"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                store_name:
                  type: string
                  description: Store name as known by the calling platform
                redirect_url:
                  type: string
                  description: 'URL Lianlian will redirect to at the end of a successful registration process.  '
                shop_url:
                  type: string
                  description: URL of merchant store if URL canâ€™t be algorithmically produced from merchant_id
                note:
                  type: string
                  description: Note to be used by customer support if needed
                merchant_client_id:
                  type: string
                  description: Merchant ID as known by the client platform
              required:
                - merchant_client_id
                - store_name
                - redirect_url
      tags:
        - Merchants
  '/merchants/merchant_client_id/{merchant_client_id}':
    parameters:
      - schema:
          type: string
        name: merchant_client_id
        in: path
        required: true
    get:
      summary: Get Merchant
      tags:
        - Merchants
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchant'
              examples:
                Example:
                  value:
                    shop_url: 'https://www.wish.com/merchant/wish001'
                    registration_complete: true
                    id: '8866003800000564'
                    status: success
                    merchant_client_id: wish001
        '404':
          description: Not Found
      operationId: get-merchants-merchant.id
      description: Get information about the merchant - in particular their status on the LianLian platform.
  /payments:
    parameters: []
    post:
      summary: Send Payment to Merchant
      operationId: post-merchants-merchant_id-payments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
              examples:
                Example:
                  value:
                    status: ongoing
                    currency: USD
                    amount: '123.30'
                    note: USD
                    merchant_id: '8866003600000853'
                    id: '2020012026476843'
                    payment_client_id: wish001
                    merchant_client_id: test1021
        '400':
          description: |-
            Error - payment not processed

            | Code | Message | Client Action | LianLian Action |
            |------|---------|-------|---------|
            |154008 | Client has insufficient balance to pay merchant| Client to wire more funds to LianLian account | Waits for funds |
            |154011 | Currency not supported| Client validates Currency used in request. Supported currencies: **USD**, **CNY** |Waits for a new request|
            |154016 | Merchant is blocked from receiving payments| Suggest merchant to contact LianLian for details |Is typically having offline discussion with merchant|
            |999995 | Invalid Parameter|Client updates request body values according to error code returned by LianLian.|Waits for a new request|
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                '154011':
                  value:
                    code: '154011'
                    message: Currency not supported.
                '154016':
                  value:
                    code: '154016'
                    message: Merchant is blocked from receiving payments.
                '999995':
                  value:
                    code: '999995'
                    message: "[merchant_client_id] can't be empty."
      description: "Initiates a payment to specific merchant. \n\nThis call is Idempotent if sent with the same payment_client_id and last payment request was successfull.  In this case the additional HTTP Response Header `Request-Repeated: true` will be returned.  If the original request failed, a new payment request will retry the payment.\n\nSteps within API:\n\n* **Money Debited** from client's account\n can fail from insufficient funds\n* **Verify Merchant Registration** information is valid\n  If Merchant is unknown, call fails\n  If Merchant status is `blocked`, call fails \n* **Send Money** to merchant\n  If any issues arise, LianLian customer support helps fix issues and finalize transfer\n\nThis call returns HTTP Status 200 on success and returns the payment object including Lianlian internal payment status. Success guarantees the money has been debited from the client account not that the actual payment has completed as it takes too long to be done synchronously and will be completed within a few days typically.  It does guarantee, however, that the payment will eventually happen.\n\nOn failure the API returns HTTP Status 400 with an Error object specifying the error code why the payment failed.\n"
      tags:
        - Payments
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_client_id:
                  type: string
                  description: "Client's Merchant ID to make payment to."
                payment_client_id:
                  type: string
                  description: "Client's Payment ID for this payment request.  **Must be unique and is usually a UUID**"
                currency:
                  type: string
                  description: 3 letter code of payment currency
                  enum:
                    - CNY
                    - USD
                amount:
                  type: number
                  description: Amount to pay merchant
                note:
                  type: string
                  description: Additional information to help track payment
              required:
                - merchant_client_id
                - payment_client_id
                - currency
                - amount
        description: ''
  '/payments/payment_client_id/{payment_client_id}':
    parameters:
      - schema:
          type: string
        name: payment_client_id
        in: path
        required: true
    get:
      summary: Get Payment
      tags:
        - Payments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
              examples:
                Example:
                  value:
                    status: success
                    currency: USD
                    amount: '123.30'
                    note: rft
                    merchant_id: '8866003600000853'
                    id: '2020011923354002'
                    payment_client_id: wish001
                    merchant_client_id: test1021
        '404':
          description: Not Found
        '':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
      operationId: get-merchants-merchant_id-payments-client_id-payment_id
      description: "Get a Merchant's Payment Object including internal Lianlian payment status.\n\nThe API returns HTTP Status 200 with the related payment object if the payment was successful.  \n\nThe API returns HTTP Status 404 if the `POST /payments` call returned an error as the **payment_client_id** is not in the system and not recognized."
  /balance:
    get:
      summary: Get Client Balance
      tags:
        - Balance
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    currency:
                      type: string
                      description: 3 letter currency code
                    balance:
                      type: string
                      description: Total balance for this currency
                  required:
                    - currency
                    - Balance
              examples:
                Example:
                  value:
                    - currency: USD
                      balance: '4182.28'
                    - currency: CNY
                      balance: '78.99'
        '400':
          description: |-
            Codes:

            | Code | Description |Client Action | LianLian Action |
            |------|------------|--------------|-------------|
            |154011 | Currency not supported|Client validates Currency used in request. Supported currency: **USD**, **CNY** |Waits for a new request|
            |999995 | Invalid Parameter |Client updates request body values according to error code returned by Lianlian.|Waits for a new request|
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                '154011':
                  value:
                    code: '154011'
                    message: Currency not support.
                '999995':
                  value:
                    code: '999995'
                    message: "[merchant_client_id] can't be empty."
      operationId: get-balance
      parameters:
        - schema:
            type: string
          in: query
          name: currency
          description: Repeat parameter to specify one 3 letter currency codes to return balance in.
      description: "Returns Total balance of client's account within LianLian in one or more currencies.  Not specifying a currency will return the default currencies configured for client.  \n\nTypically this is USD & CNY."
    parameters: []
components:
  schemas:
    Merchant:
      title: '| Merchant Object'
      type: object
      x-tags:
        - Merchants
      description: Merchant object today focused on registration status
      x-examples:
        Example: {}
      properties:
        id:
          type: string
          description: |-
            LianLian merchant ID. Merchant shall use this ID to contact LianLian for any payment issues.

            Non-existant if `registraton_complete` is false.
        merchant_client_id:
          type: string
          description: "Client's ID for this Merchant"
        status:
          type: string
          title: '| Registration Status Enumeration'
          description: |-
            State of merchant registration process.  Will be NULL for brand new merchant that hasn't started registration process.

            One of:

            | Value | Description |
            |--------|------------|
            | ongoing | Registration ongoing |
            | need_info | Merchant must communicate with Lianlian |
            | success | Ready for delivery money to merchant |
            | blocked | User has been blacklisted from receiving payments |
          enum:
            - need_info
            - success
            - blocked
            - ongoing
        registration_url:
          type: string
          description: "URL to redirect merchant to in order to start registration on LianLian platform. \n \nNon-existent if `registration_complete` is true."
        shop_url:
          type: string
          description: "URL of Merchant's shop.  For some clients this URL is auto-generated from `client_id`"
        note:
          type: string
          description: Human readable description of Merchant
        registration_complete:
          type: boolean
          description: |-
            State of merchant registration process.  One of:

            | Value | Description |
            |--------|------------|
            | true| Merchant registration complete, platform can issue payment to this merchant |
            | false| Merchant registration not complete yet, platform cannot issue payment to this merchant |
      required:
        - merchant_client_id
        - status
        - registration_complete
    Error:
      title: '| Error Object'
      type: object
      description: |-
        This object is returned anytime a REST request returns HTTP status other than 2xx.

        These error codes can occur regardless of API.  For API specific error codes see individual API documentation.

        | Code | Message | Client Action | LianLian Action |
        |------|---------|--|--|
        |999995 | Invalid Parameter|Client updates request body values according to error code returned by Lianlian.|Lianlian to wait for a new request|
      x-examples: {}
      properties:
        code:
          type: string
          description: Error code as described per API
        message:
          type: string
          description: Human readable message of error
      required:
        - code
        - message
    Payment:
      title: '| Payment Object'
      type: object
      description: Payment object containing payment status
      x-tags:
        - Payments
      properties:
        id:
          type: string
          description: LianLianment ID
        payment_client_id:
          type: string
          description: "Client's Payment ID for this payment request.  **Must be unique and is usually a UUID**"
        merchant_id:
          type: string
          description: "Lianlian's Merchant ID receiving payment"
        merchant_client_id:
          type: string
          description: "Client's Merchant ID receiving payment"
        status:
          type: string
          title: '| Payment Status Enumeration'
          description: |-
            This status indicates the stage payment is at within Lianlian systems.  One of:

            | Value | Description |
            |--------|------------|
            | ongoing | Payment ongoing normally |
            | need_info | Merchant must communicate with Lianlian |
            | success | Payment complete |
          enum:
            - need_info
            - success
            - ongoing
        currency:
          type: string
          description: 3 letter code of currency used
          enum:
            - CNY
            - USD
        amount:
          type: string
          description: Amount of payment in `currency`
        note:
          type: string
          description: Human readable note passed into POST /payment
      required:
        - id
        - payment_client_id
        - merchant_id
        - merchant_client_id
        - currency
        - amount
  securitySchemes: {}
tags:
  - name: Balance
  - name: Merchants
  - name: Payments
  - name: Webhook Endpoints
servers:
  - description: Sandbox
    url: 'https://global-api-sandbox.lianlianpay-inc.com/payments/v1'
